// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDge4XGPw6OVrvK_051-1ELHnU8EBIzah8',
    appId: '1:960923193223:android:f026a525be6386c924cd22',
    messagingSenderId: '960923193223',
    projectId: 'drbike-7fa3a',
    storageBucket: 'drbike-7fa3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHTfwFtF-zzpa2Rs-Xs1likTgrMCfdGyU',
    appId: '1:960923193223:ios:d469b0ccc2def00424cd22',
    messagingSenderId: '960923193223',
    projectId: 'drbike-7fa3a',
    storageBucket: 'drbike-7fa3a.firebasestorage.app',
    iosBundleId: 'com.application.doctorbike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlkFQ3tyFYXo4EI1Z2qBIlaAGaPRa0wvQ',
    appId: '1:960923193223:web:8995a7a8ef96a8e224cd22',
    messagingSenderId: '960923193223',
    projectId: 'drbike-7fa3a',
    authDomain: 'drbike-7fa3a.firebaseapp.com',
    storageBucket: 'drbike-7fa3a.firebasestorage.app',
    measurementId: 'G-J3MK6B3RQ3',
  );
}
